import {VARIETIES,ERAS,UNLOCK_COST,FRAGMENT_SLOT_SOURCE,FRAGMENT_SOURCE_LABEL} from './variety-engine.js';
export function createVariety({getState,dispatch}){
 function render(message=''){
  const s=getState(),b=s.varietyBook||{era:'清代',unlocked:[],culture:0,hybrid:false,achievement:false,artFragments:[],artRestored:false};
  const progress=b.unlocked.length/13;
  const canAfford=(s.sales?.wen||0)>=UNLOCK_COST.wen&&s.rice>=UNLOCK_COST.rice;
  const cards=VARIETIES.map(v=>{const ok=b.unlocked.includes(v.id),available=ERAS.indexOf(v.era)<=ERAS.indexOf(b.era);return `<article class="variety-card ${ok?'unlocked':''}"><div class="variety-mark">${ok?'稻':'？'}</div><div><h2>${v.name}</h2><p>${ok?`${v.period} · ${v.origin}`:`解锁时代：${v.era}`}</p><dl><dt>生育期</dt><dd>${v.growth}</dd><dt>亩产</dt><dd>${v.yield} kg</dd><dt>品质</dt><dd>${v.quality}</dd><dt>属性</dt><dd>${v.attr}</dd></dl><button data-variety="${v.id}" ${ok||!available||!canAfford?'disabled':''}>${ok?'已收录':!available?'时代未到':'送档收录'}</button></div></article>`;}).join('');
  const puzzle=Array.from({length:20},(_,i)=>`<span class="fragment-slot ${b.artFragments?.includes(i)?'found':''}" title="${b.artFragments?.includes(i)?'已寻得 · 来自'+(FRAGMENT_SOURCE_LABEL[FRAGMENT_SLOT_SOURCE[i]]||''):'来自'+(FRAGMENT_SOURCE_LABEL[FRAGMENT_SLOT_SOURCE[i]]||'')}">${b.artFragments?.includes(i)?'◇':'？'}</span>`).join('');
  document.querySelector('#variety-root').innerHTML=`<div class="book-heading"><span>御贡图鉴 · 京西稻十三珍</span><h1>老品种活态谱系</h1><p>收集进度 ${b.unlocked.length} / 13 · 文化碎片 ${b.culture} · 当前时代 ${b.era}</p></div><div class="book-progress"><i style="width:${progress*100}%"></i></div><section class="era-line">${ERAS.map(e=>`<button data-era="${e}" class="${e===b.era?'active':''}" ${ERAS.indexOf(e)>ERAS.indexOf(b.era)+1?'disabled':''}>${e}</button>`).join('')}</section>  <section class="breeding-card"><h2>农科所 · 杂交育种</h2><p>投入 120 文 + 300 kg 稻米，消耗水源三百粒与越路早生（图鉴中的越富系三）亲本，培育京越一号。</p><button data-book="hybrid" ${b.hybrid?'disabled':''}>${b.hybrid?'杂交育种已解锁':'投入资源解锁'}</button></section><section class="variety-grid">${cards}</section><p class="variety-cost-hint">收录一个老品种需送档案房整理：${UNLOCK_COST.wen} 文 + ${UNLOCK_COST.rice} kg 稻米（当前持有 ${(s.sales?.wen||0).toLocaleString()} 文 · ${s.rice} kg）。</p><section class="art-puzzle"><h2>《京西稻耕织图》拼图</h2><p>碎片 ${b.artFragments?.length||0} / 20 · 碎片只能靠玩出来：种植收获、作坊加工、市场交易、社交认养、穿越剧情各掉一组，不能自己点开</p><div class="puzzle-grid">${puzzle}</div>${b.artRestored?'<div class="book-achievement">卷轴已补全 · 称号：京西稻文化遗产守护者</div>':'<div class="book-achievement pending">卷轴未补全，尚缺 '+(20-(b.artFragments?.length||0))+' 片。</div>'}</section>${b.achievement?'<div class="book-achievement">成就解锁：京西稻活态基因库</div>':''}<div class="book-message" role="status">${message}</div>`;
  document.querySelectorAll('[data-era]').forEach(x=>x.onclick=()=>dispatch({type:'book:era',era:x.dataset.era}));document.querySelectorAll('[data-variety]').forEach(x=>x.onclick=()=>dispatch({type:'book:unlock',id:x.dataset.variety}));document.querySelector('[data-book="hybrid"]')?.addEventListener('click',()=>dispatch({type:'book:hybrid'}));
 }
 return {render};
}
